version: "3"

services:
  postgres:
    image: postgres:latest
    networks:
      - postgres
    volumes:
      - ~/data/postgres:/data/postgres
    env_file:
      - docker.env
 
  pgadmin:
    image: dpage/pgadmin4
    networks:
      - postgres
    ports:
      - "8080:80"
    volumes:
      - ~/data/pgadmin:/root/.pgadmin
    env_file:
      - docker.env
 
  nestjs-api:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - "3000:3000"
    volumes:
      - .:/usr/src/app
    depends_on:
      - postgres
    networks:
      - postgres
 
networks:
  postgres:
    driver: bridge